/* Autogenerated by pngtolights.py */

#include <Arduino.h>
#include <avr/pgmspace.h>
#define RGAM_DATA_COLUMNS 84
#define RGAM_DATA_ROWS 8
#define RGAM_COLORS 3
extern byte data[RGAM_DATA_COLUMNS][RGAM_DATA_ROWS][RGAM_COLORS] PROGMEM;
